name: Ubuntu Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
    
    - name: Install gcc-11
      run: |
        sudo apt install build-essential manpages-dev software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install gcc-11 g++-11

    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.2.0'
        host: 'linux'
        target: 'desktop'
        install-deps: 'true'
    
    - name: Find Qt 6
      if: ${{ startsWith(matrix.qt_ver, '6') }}
      run: |
        echo 'Qt6_DIR = ${{ env.Qt6_DIR }}'
        echo 'Qt_DIR=${{ env.Qt6_DIR }}' >> ${GITHUB_ENV}
    
    - name: Configure Qt env
      run: echo '${{ env.Qt_DIR }}/bin' >> ${GITHUB_PATH}
    
    - name: Test Qt & env
      run: |
        echo ${PATH}
        which 'qmake'
        qmake '-query'
    
    - uses: actions/checkout@v2   
    - name: Configure CMake
      env:  
        CMAKE_PREFIX_PATH: ${{env.Qt6_DIR}}
      run: |
        rm -f CMakeCache.txt
        CXX=g++-11 CC=gcc-11 cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: CXX=g++-11 CC=gcc-11 cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
